services:
  app:
    build: .
    ports:
      - "5685:5685"
    environment:
      - NODE_ENV=production
      - PORT=5685
      - REDIS_URL=redis://redis:6379
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_WHISPER_MODEL=${GROQ_WHISPER_MODEL:-distil-whisper-large-v3-en}
      - GROQ_BASE_URL=${GROQ_BASE_URL:-https://api.groq.com/openai/v1}
    volumes:
      - audio_data:/app/audio_file
      - models_data:/app/models
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - transcripts-network

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - transcripts-network

volumes:
  audio_data:
  models_data:
  redis_data:

networks:
  transcripts-network:
    external: false
    driver: bridge